@echo off
echo ============================================
echo   Updating Game Data from puzzles.txt
echo ============================================
echo.

:: Read puzzles.txt and wrap it into puzzles-data.js
echo // AUTO-GENERATED — Do not edit this file directly. > puzzles-data.js
echo // Edit puzzles.txt instead, then run update-puzzles.bat >> puzzles-data.js
echo var PUZZLE_TEXT = ^` >> puzzles-data.js
type puzzles.txt >> puzzles-data.js
echo ^`; >> puzzles-data.js

echo.
echo Done! Game data updated from puzzles.txt
echo You can now open index.html in your browser.
echo ============================================
pause
